/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { FiFacebook } from "react-icons/fi";
import { BsInstagram } from "react-icons/bs";
import { FiGithub } from "react-icons/fi";
import { HiMenu } from "react-icons/hi";


// import {IoCloseSharp, } from "react-icons/io"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sophie</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <div>
          <nav>
            <div className="container">
              <a href="#">
                <h3>Sophie</h3>
              </a>
              <ul>
                <li>
                  <a href="#">Home</a>
                </li>
                <li>
                  <a href="#About">About</a>
                </li>
                <li>
                  <a href="#Experience">Experience</a>
                </li>
                <li>
                  <a href="#contact">Contact</a>
                </li>
              </ul>

              <button>
                <HiMenu />
              </button>
            </div>
          </nav>

          <section className="landing">
            <div className="container">
              <div className="socials">
                <a
                  href="https://facebook.com/"
                  target="_blank"
                  rel="noreferrer"
                >
                  <FiFacebook />
                </a>
                <a
                  href="https://instagram.com"
                  target="_blank"
                  rel="noreferrer"
                >
                  <BsInstagram />
                </a>
                <a href="https:github.com" target="_blank" rel="noreferrer">
                  <FiGithub />
                </a>
              </div>

              <div className="info">
                <h1>Jr.Front-end Web Developer and Traveler</h1>
                <p>
                  I'm a Junior Web Designer and Adventurous Traveler from
                  Taiwan. And I'm very creative and passionate at my work. It's
                  very nice to meet you.
                </p>
              </div>

              <div className="circle--square">
                <img src="./images/img_pro.png" />
              </div>
            </div>
          </section>
        </div>

        <section className="about" id="about">
          <div className="container">
            <h1>About Me</h1>
          </div>
          <div className="container">
            <img src="./images/img_pro.png" />
          </div>
          <div className="container">
            <h5>
              Name: Sophie Hsu
              <hr />
              Nationality: Taiwan
              <hr />
              Location: Phillipines
              <hr />
              Language: Chinese/English
              <hr />
              Interests: Travel/Photograph /Music <hr />
              <hr />
              -----Currently living in Phillipines, fonds of learning, recently
              learning front-end Developer and my goal is become a impressive
              front-end Developer.
            </h5>
          </div>
        </section>
        <section className="aboutmore">
          <p>my strength</p>
          <div className="wrap">
            <h2>Ambition</h2>
            <p>Always having strong desire to do or to achieve succrss.</p>
          </div>
          <div className="wrap">
          <h2>Challenge</h2>
            <p>Never be afraid to Challenge myself.</p>
          </div>
          <div className="wrap">
            <h2>Adventure</h2>
            <p>Adventure makes me feel alive!</p>
          </div>
        </section>
      </main>

      {/* <footer className={styles.footer}>
        <a
          // target="_blank"
          // rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          Made by Sophie</span>
        </a>
      </footer> */}

      <footer className="footer">
        <p>Made by Sophie</p>
      </footer>
    </div>
  );
}
