/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @next/next/no-img-element */

import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import {FiFacebook, } from "react-icons/fi"
import {BsInstagram, } from "react-icons/bs"
import {FiGithub, } from "react-icons/fi"


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sophie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <nav>
            <div class="container">
              <a href="#">
                <h3>Sophie</h3>
              </a>
              <ul>
                <li> 
                  <a href="#">Home</a>
                </li>
                <li>
                  <a href="#About">About</a>
                </li>
                <li>
                  <a href="#Experience">Experience</a>
                </li>
                <li>
                  <a href="#contact">Contact</a>
                </li>
              </ul>
              <button>
                <span class="material-symbols-sharp">menu</span>
              </button>
              <button>
                <span class="material-symbols-sharp">close</span>
              </button>
            </div>
          </nav>

          <section class="landing">
            <div class="container">
              <div class="socials">
              <a href="https://facebook.com/" target="_blank"><FiFacebook/></a>
                <a href="https://instagram.com" target="_blank"><BsInstagram/></a>
               <a href="https:github.com" target="_blank"><FiGithub/></a>
              </div>

              <div class="info">
                <h1>Jr.Front-end Web Developer & Traveler</h1>
                <h3>Hello I,m Sophie</h3>
                <p>
                  Im a Junior Web Designer and Adventurous Traveler from Taiwan. And I'm very creative and passionate at my work. It's very nice to meet you.
                </p>
                
              </div>

              <div class="circle--square">
                <img src="./images/img_pro.png" />
              </div>
            </div>
          </section>
        </div>

        <section class="about" id="about">
          <h1>About</h1>
          <div class="container">
            <div class="image">
              <img src="./images/img_pro.png" />
            </div>
            <div class="content">
              <i class="uil uil-check-circle"></i>
              <p>Name: Sophie Hsu</p>
              <i class="uil uil-check-circle"></i>
              <p>Birthday:1993/06/01 </p>
              <i class="uil uil-check-circle"></i>
              <p>Nationality: Taiwan</p>
              <i class="uil uil-check-circle"></i>
              <p>Education: Tunghai University</p>
              <i class="uil uil-check-circle"></i> <p>Location: Phillipines</p>
              <i class="uil uil-check-circle"></i>{" "}
              <p>Language: Chinese/English/Japanese</p>
            </div>
          </div>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
